all: HW0 HW1 HW2

HW0: ./homework/HW0/Hw0.tex
    latexmk -pdf -jobname=./homework/HW0/Hw0 ./homework/HW0/Hw0.tex

HW1: ./homework/HW1/Hw1.tex
    latexmk -pdf -jobname=./homework/HW1/Hw1 ./homework/HW1/Hw1.tex

HW2: ./homework/HW2/HW2.tex
    latexmk -pdf -jobname=./homework/HW2/HW2 ./homework/HW2/HW2.tex

clean:
	latexmk -c -jobname=./homework/HW0/Hw0
	latexmk -c -jobname=./homework/HW1/Hw1
	latexmk -c -jobname=./homework/HW2/HW2
